version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
  reviewers:
  - Armitage35
  labels:
  - dependencies
  ignore:
  - dependency-name: core-js
    versions:
    - 3.8.3
    - 3.9.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: vue-router
    versions:
    - 3.5.1
  - dependency-name: sass-loader
    versions:
    - 10.1.0
    - 10.1.1
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
